source 'https://rubygems.org'
ruby '2.0.0'
gem 'logger'
gem 'sinatra'
gem 'pry'
gem 'pry-debugger'
gem 'haml'
gem 'addressable', require: 'addressable/uri'
gem 'builder'
gem 'capybara'
gem 'poltergeist', require: 'capybara/poltergeist'
gem 'thin'
