source 'https://rubygems.org'
ruby '1.9.3'
gem 'logger'
gem 'sinatra'
gem 'pry'
gem 'haml'
gem 'addressable', require: 'addressable/uri'
gem 'builder'
gem 'capybara'
gem 'poltergeist', "1.4.1", require: 'capybara/poltergeist'
gem 'thin'
gem 'sinatra-contrib'
